#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H


#define EXTINTERRUPT0 (0x00)
#define EXTINTERRUPT1 (0x01)
#define EXTINTERRUPT2 (0x02)
#define EXTINTERRUPT0_PIN1 (0x00)
#define EXTINTERRUPT0_PIN2 (0x01)
#define EXTINTERRUPT1_PIN1 (0x02)
#define EXTINTERRUPT1_PIN2 (0x03)
#define EXTINTERRUPT2_PIN1 (0x06)
#define EXTINTERRUPT0_REQUEST_PIN (0x06)
#define EXTINTERRUPT1_REQUEST_PIN (0x07)
#define EXTINTERRUPT2_REQUEST_PIN (0x05)
#define RISING_EDGE 0
#define FALLING_EDGE 1
#define LOW_LEVEL 2
#define ANY_LOGICAL_CHANGE 3


#endif